"""Clinical PDF report (W10) via ReportLab.

Patient info + per-disease prediction/confidence/risk + original image + Grad-CAM +
a rule-based recommendation (Healthy / Follow-up / Refer / Urgent) + a prominent
"not a diagnostic device" disclaimer. Used by the web app's "Download PDF report".
"""
from __future__ import annotations

import io
from datetime import datetime
from pathlib import Path

DISCLAIMER = (
    "This report is generated by an AI-assisted retinal screening prototype intended "
    "to SUPPORT, not replace, an ophthalmologist. It is not a regulated diagnostic "
    "device and has not undergone prospective clinical or regulatory validation. "
    "All findings must be confirmed by a qualified clinician."
)

# Rule-based risk + recommendation per disease grade.
RISK_RULES = {
    "DR": {0: ("Low", "Healthy retina — routine annual screening."),
           1: ("Mild", "Follow-up recommended in 6–12 months."),
           2: ("Moderate", "Refer to ophthalmologist."),
           3: ("High", "Refer to ophthalmologist (priority)."),
           4: ("Critical", "Urgent specialist consultation.")},
    "ROP": {0: ("Low", "No ROP signs — continue scheduled screening."),
            1: ("High", "Signs of ROP — urgent ophthalmology review.")},
    "Glaucoma": {0: ("Low", "No glaucomatous signs — routine screening."),
                 1: ("High", "Refer to ophthalmologist for glaucoma work-up.")},
}


def recommendation(disease: str, grade: int):
    return RISK_RULES.get(disease, {}).get(grade, ("Unknown", "Clinician review advised."))


def _to_reader(image):
    """Accept a PIL image or a path -> ReportLab ImageReader."""
    from reportlab.lib.utils import ImageReader
    from PIL import Image
    if image is None:
        return None
    if not hasattr(image, "save"):
        image = Image.open(image).convert("RGB")
    buf = io.BytesIO()
    image.convert("RGB").save(buf, format="PNG")
    buf.seek(0)
    return ImageReader(buf)


def generate_pdf(out_path, patient: dict, findings: list[dict],
                 original_image=None, gradcam_image=None) -> str:
    """findings: [{"disease","prediction","score","grade"}, ...]."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    out_path = str(out_path)
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(out_path, pagesize=A4)
    W, H = A4

    # header
    c.setFillColorRGB(0.06, 0.09, 0.16)
    c.rect(0, H - 28 * mm, W, 28 * mm, fill=1, stroke=0)
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(18 * mm, H - 16 * mm, "AI-Assisted Retinal Screening Report")
    c.setFont("Helvetica", 9)
    c.drawString(18 * mm, H - 22 * mm, "Clinical decision-support prototype — screening assistant")

    # patient block
    y = H - 40 * mm
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(18 * mm, y, "Patient")
    c.setFont("Helvetica", 10)
    fields = [("Name", patient.get("name", "—")), ("Patient ID", patient.get("id", "—")),
              ("Age", str(patient.get("age", "—"))), ("Gender", patient.get("gender", "—")),
              ("Date", patient.get("date", datetime.now().strftime("%Y-%m-%d")))]
    # The screening context determines which models were eligible to run, so it is part of
    # the clinical provenance of this report, not decoration.
    if patient.get("context_label"):
        fields.append(("Screening context", patient["context_label"]))
    for i, (k, v) in enumerate(fields):
        c.drawString(18 * mm, y - (6 + i * 6) * mm, f"{k}: {v}")

    # findings table
    y2 = y - 6 * mm
    c.setFont("Helvetica-Bold", 11)
    c.drawString(95 * mm, y, "AI Findings")
    c.setFont("Helvetica", 10)
    row = 0
    for f in findings:
        disease = f["disease"]
        # A model that never ran must NEVER be rendered as a clinical result. Before this
        # guard, a routed-out disease fell through to recommendation(disease, 0) and printed
        # "Healthy retina — routine annual screening" for a model that was never executed.
        if not f.get("available", True):
            label = ("Not assessed" if f.get("status") == "not_applicable"
                     else "Not available")
            c.setFont("Helvetica-Bold", 10)
            c.setFillColorRGB(0.42, 0.42, 0.45)
            c.drawString(95 * mm, y2 - (row * 14) * mm, f"{disease}: {label}")
            c.setFont("Helvetica", 8)
            for i, line in enumerate(_wrap(f.get("note", "This model was not run."), 52)[:2]):
                c.drawString(95 * mm, y2 - (row * 14 + 4.5 + i * 3.5) * mm, line)
            c.setFillColorRGB(0, 0, 0)
            row += 1
            continue
        grade = int(f.get("grade", 0))
        risk, rec = recommendation(disease, grade)
        c.setFont("Helvetica-Bold", 10)
        c.drawString(95 * mm, y2 - (row * 14) * mm,
                     f"{disease}: {f['prediction']}  ({f.get('score', 0):.1f}%)")
        c.setFont("Helvetica", 9)
        c.drawString(95 * mm, y2 - (row * 14 + 5) * mm, f"Risk: {risk} — {rec}")
        row += 1

    # images
    img_y = y - 110 * mm
    orig = _to_reader(original_image)
    cam = _to_reader(gradcam_image)
    if orig:
        c.setFont("Helvetica-Bold", 9); c.drawString(18 * mm, img_y + 67 * mm, "Fundus image")
        c.drawImage(orig, 18 * mm, img_y, width=75 * mm, height=65 * mm, preserveAspectRatio=True)
    if cam:
        c.setFont("Helvetica-Bold", 9); c.drawString(105 * mm, img_y + 67 * mm, "AI heatmap (Grad-CAM)")
        c.drawImage(cam, 105 * mm, img_y, width=75 * mm, height=65 * mm, preserveAspectRatio=True)

    # disclaimer
    c.setFillColorRGB(0.6, 0.1, 0.1)
    c.setFont("Helvetica-Oblique", 8)
    text = c.beginText(18 * mm, 22 * mm)
    for line in _wrap(DISCLAIMER, 110):
        text.textLine(line)
    c.drawText(text)

    c.showPage()
    c.save()
    return out_path


def _wrap(s, width):
    words, line, out = s.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > width:
            out.append(line); line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out
